package com.abonex.abonexbackend.entity.enums;

public enum NotificationType {
    UPCOMING_PAYMENT,
    SUBSCRIPTION_EXPIRED,
    PAYMENT_OVERDUE,
    ACCOUNT_REACTIVATION_CODE_SENT,
    ACCOUNT_ACTIVATED,
    WELCOME_MESSAGE,
    PAYMENT_CONFIRMED,
    SUBSCRIPTION_CANCELLED
}
